## 3. Calculate similarity measures for a given dataset

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
from scipy.stats import pearsonr

In [2]:
df = pd.read_csv("C:\\Users\HP-LSC-001\\Desktop\\Goura Nachika Recommend System LAB\\Experiment 3\\ratings.csv")   # <-- change the file name if needed

print("Raw Dataset:")
display(df)

Raw Dataset:

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [3]:
ratings_matrix = df.pivot_table(index='userId', 
                                columns='movieId', 
                                values='rating').fillna(0)

ratings_matrix

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Cosine Similarity (User–User)

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim = pd.DataFrame(
    cosine_similarity(ratings_matrix),
    
    index=ratings_matrix.index,
    columns=ratings_matrix.index
)

print("Cosine Similarity Matrix:")
cos_sim

Cosine Similarity Matrix:

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.164191,0.028429,0.012993,0.200395,0.106435,0.102123,0.200035,0.099388,0.075898,0.088963,...,0.178084,0.116534,0.300669,0.066032,0.148141,1.000000,0.153063,0.262558,0.069622,0.201104
607,0.269389,0.012948,0.019247,0.131746,0.152866,0.162182,0.186114,0.185142,0.011844,0.010451,...,0.092525,0.199910,0.203540,0.137834,0.118780,0.153063,1.000000,0.283081,0.149190,0.139114
608,0.291097,0.046211,0.021128,0.149858,0.135535,0.178809,0.323541,0.187233,0.100435,0.077424,...,0.158355,0.197514,0.232771,0.155306,0.178142,0.262558,0.283081,1.000000,0.121993,0.322055
609,0.093572,0.027565,0.000000,0.032198,0.261232,0.214234,0.090840,0.423993,0.000000,0.021766,...,0.035653,0.335231,0.061941,0.236601,0.097610,0.069622,0.149190,0.121993,1.000000,0.053225
610,0.145321,0.102427,0.032119,0.107683,0.060792,0.052668,0.193219,0.078153,0.074399,0.121072,...,0.222491,0.087528,0.163094,0.052552,0.119295,0.201104,0.139114,0.322055,0.053225,1.000000

## Pearson Similarity

In [5]:
pearson_sim = ratings_matrix.T.corr(method='pearson')

print("Pearson Similarity Matrix:")
pearson_sim

Pearson Similarity Matrix:

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.019400,0.053056,0.176920,0.120866,0.104418,0.143793,0.128547,0.055268,-0.000298,...,0.066256,0.149942,0.186978,0.056530,0.134412,0.121981,0.254200,0.262241,0.085434,0.098719
2,0.019400,1.000000,-0.002594,-0.003804,0.013183,0.016257,0.021567,0.023750,-0.003448,0.061880,...,0.198549,0.010888,-0.004030,-0.005345,-0.007919,0.011299,0.005813,0.032730,0.024373,0.089329
3,0.053056,-0.002594,1.000000,-0.004556,0.001887,-0.004577,-0.005634,0.001703,-0.003111,-0.005501,...,0.000150,-0.000585,0.011211,-0.004822,0.003678,-0.003246,0.012885,0.008096,-0.002963,0.015962
4,0.176920,-0.003804,-0.004556,1.000000,0.121018,0.065719,0.100602,0.054235,0.002417,0.015615,...,0.072848,0.114287,0.281866,0.039699,0.065493,0.164831,0.115118,0.116861,0.023930,0.062523
5,0.120866,0.013183,0.001887,0.121018,1.000000,0.294138,0.101725,0.426576,-0.004185,0.023471,...,0.061912,0.414931,0.095394,0.254117,0.141077,0.090158,0.145764,0.122607,0.258289,0.040372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.121981,0.011299,-0.003246,0.164831,0.090158,0.047506,0.172499,0.081913,0.057989,0.054877,...,0.153892,0.084208,0.224637,0.035251,0.106752,1.000000,0.115999,0.188354,0.052385,0.093851
607,0.254200,0.005813,0.012885,0.115118,0.145764,0.142169,0.173293,0.178133,0.003257,-0.004809,...,0.080034,0.187588,0.173025,0.126267,0.101138,0.115999,1.000000,0.258245,0.142533,0.098518
608,0.262241,0.032730,0.008096,0.116861,0.122607,0.137954,0.305439,0.175912,0.086229,0.048373,...,0.136316,0.174069,0.164479,0.133734,0.144896,0.188354,0.258245,1.000000,0.109563,0.248944
609,0.085434,0.024373,-0.002963,0.023930,0.258289,0.207124,0.084494,0.421627,-0.003937,0.014983,...,0.029664,0.331053,0.046000,0.232115,0.089810,0.052385,0.142533,0.109563,1.000000,0.033713
610,0.098719,0.089329,0.015962,0.062523,0.040372,-0.010400,0.163775,0.058168,0.055265,0.087036,...,0.200487,0.050806,0.064594,0.018502,0.072727,0.093851,0.098518,0.248944,0.033713,1.000000

## Euclidean Similarity

In [6]:
from sklearn.metrics import euclidean_distances

dist = pd.DataFrame(
    euclidean_distances(ratings_matrix),
    index=ratings_matrix.index,
    columns=ratings_matrix.index
)

euclidean_sim = 1 / (1 + dist)

print("Euclidean Similarity Matrix:")
euclidean_sim

Euclidean Similarity Matrix:

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.013999,0.014217,0.012532,0.014289,0.011396,0.013305,0.014309,0.014046,0.012567,...,0.012659,0.013499,0.008371,0.013308,0.012774,0.007544,0.013330,0.009931,0.014347,0.006926
2,0.013999,1.000000,0.032833,0.016476,0.029580,0.014754,0.020550,0.029474,0.030185,0.021626,...,0.021475,0.021246,0.008606,0.023437,0.018245,0.007889,0.017125,0.010204,0.033176,0.007292
3,0.014217,0.032833,1.000000,0.016635,0.030411,0.014775,0.020644,0.030125,0.031274,0.021383,...,0.020055,0.021499,0.008647,0.023931,0.018542,0.007885,0.017343,0.010184,0.034138,0.007223
4,0.012532,0.016476,0.016635,1.000000,0.016939,0.012221,0.014847,0.016466,0.016318,0.014444,...,0.014418,0.015199,0.009020,0.015271,0.013859,0.007887,0.013714,0.009603,0.016781,0.006998
5,0.014289,0.029580,0.030411,0.016939,1.000000,0.016116,0.020674,0.035833,0.028218,0.020611,...,0.019720,0.025606,0.008742,0.025763,0.018939,0.007978,0.017728,0.010370,0.034893,0.007225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.007544,0.007889,0.007885,0.007887,0.007978,0.007411,0.008044,0.007964,0.007940,0.007776,...,0.007964,0.007846,0.007045,0.007800,0.007818,1.000000,0.007768,0.007322,0.007954,0.006013
607,0.013330,0.017125,0.017343,0.013714,0.017728,0.012951,0.015859,0.017942,0.016895,0.014680,...,0.014833,0.016261,0.008614,0.016402,0.014446,0.007768,1.000000,0.010378,0.018118,0.007111
608,0.009931,0.010204,0.010184,0.009603,0.010370,0.009440,0.010844,0.010509,0.010298,0.009796,...,0.010013,0.010283,0.007624,0.010241,0.009961,0.007322,0.010378,1.000000,0.010394,0.007130
609,0.014347,0.033176,0.034138,0.016781,0.034893,0.015733,0.021361,0.038761,0.031187,0.021537,...,0.020262,0.024904,0.008701,0.026679,0.019108,0.007954,0.018118,0.010394,1.000000,0.007244
610,0.006926,0.007292,0.007223,0.006998,0.007225,0.006725,0.007348,0.007246,0.007250,0.007202,...,0.007408,0.007134,0.006108,0.007124,0.007112,0.006013,0.007111,0.007130,0.007244,1.000000

## Jaccard Similarity (for implicit rating)

In [7]:
binary_matrix = ratings_matrix.applymap(lambda x: 1 if x > 0 else 0)

jaccard_sim = pd.DataFrame(index=binary_matrix.index, columns=binary_matrix.index)

for u1 in binary_matrix.index:
    for u2 in binary_matrix.index:
        intersection = (binary_matrix.loc[u1] & binary_matrix.loc[u2]).sum()
        union = (binary_matrix.loc[u1] | binary_matrix.loc[u2]).sum()
        jaccard_sim.loc[u1, u2] = intersection / union

print("Jaccard Similarity Matrix:")
jaccard_sim

Jaccard Similarity Matrix:

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.0,0.007722,0.026515,0.111663,0.04943,0.064327,0.072626,0.056818,0.018315,0.016393,...,0.034161,0.079412,0.103286,0.0375,0.083732,0.066508,0.167131,0.14671,0.034615,0.047099
2,0.007722,1.0,0.0,0.004098,0.013889,0.005865,0.016854,0.013333,0.0,0.030488,...,0.092437,0.006135,0.002062,0.0,0.0,0.00439,0.004651,0.007026,0.015385,0.013709
3,0.026515,0.0,1.0,0.003937,0.012195,0.008571,0.0,0.011765,0.0,0.0,...,0.014493,0.011628,0.00925,0.0,0.003861,0.006981,0.018018,0.010453,0.0,0.005247
4,0.111663,0.004098,0.003937,1.0,0.048387,0.053678,0.063584,0.035433,0.003831,0.025937,...,0.049669,0.070122,0.136275,0.029316,0.038005,0.077733,0.07754,0.076053,0.012,0.036177
5,0.04943,0.013889,0.012195,0.048387,1.0,0.111801,0.048128,0.263889,0.0,0.016575,...,0.028369,0.209459,0.025988,0.152,0.055777,0.020246,0.069444,0.035503,0.140845,0.010511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.066508,0.00439,0.006981,0.077733,0.020246,0.046886,0.068297,0.020193,0.013089,0.032922,...,0.046472,0.038206,0.176672,0.019295,0.057799,1.0,0.061125,0.150118,0.013193,0.101641
607,0.167131,0.004651,0.018018,0.07754,0.069444,0.077419,0.090032,0.073394,0.00431,0.015528,...,0.039711,0.098976,0.091787,0.070896,0.05974,0.061125,1.0,0.128603,0.056604,0.042717
608,0.14671,0.007026,0.010453,0.076053,0.035503,0.10735,0.11959,0.047733,0.020955,0.028602,...,0.042506,0.07933,0.14157,0.060364,0.078974,0.150118,0.128603,1.0,0.027219,0.161132
609,0.034615,0.015385,0.0,0.012,0.140845,0.066869,0.032787,0.253731,0.0,0.011429,...,0.014706,0.154362,0.013444,0.113821,0.036145,0.013193,0.056604,0.027219,1.0,0.007524
610,0.047099,0.013709,0.005247,0.036177,0.010511,0.019558,0.059767,0.012763,0.010495,0.038157,...,0.051724,0.020597,0.077255,0.012274,0.043151,0.101641,0.042717,0.161132,0.007524,1.0